import { integer, pgTable, text, timestamp } from "drizzle-orm/pg-core";

export const persons = pgTable("persons", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  generation: integer("generation").notNull(),
  parentId: text("parent_id"),
  children: text("children").array(),
  birthRank: integer("birth_rank"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export const metadata = pgTable("metadata", {
  key: text("key").primaryKey(),
  value: integer("value").notNull(),
});

export type Persons = typeof persons.$inferSelect;

export const schema = { persons, metadata };

export const initialFamilyData = [
  {
    id: "1",
    name: "Joseph OKISSI",
    generation: 1,
    parentId: null,
    children: [
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
    ],
    birthRank: 1,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "2",
    name: "Anne-Marie OGANDAGA Eps OKISSI",
    generation: 1,
    parentId: null,
    children: [
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
    ],
    birthRank: 2,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "3",
    name: "Jean Bernard OKISSI",
    generation: 2,
    parentId: "1",
    children: [],
    birthRank: 1,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "4",
    name: "Florian OKISSI",
    generation: 2,
    parentId: "1",
    children: [],
    birthRank: 2,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "5",
    name: "Rose Colette OKISSI",
    generation: 2,
    parentId: "1",
    children: [],
    birthRank: 3,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "6",
    name: "Richard OKISSI",
    generation: 2,
    parentId: "1",
    children: [],
    birthRank: 4,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "7",
    name: "Guy-Joel OKISSI",
    generation: 2,
    parentId: "1",
    children: [],
    birthRank: 5,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "8",
    name: "Anicet OKISSI",
    generation: 2,
    parentId: "1",
    children: [],
    birthRank: 6,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "9",
    name: "Blaise OKISSI",
    generation: 2,
    parentId: "1",
    children: [],
    birthRank: 7,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "10",
    name: "Octavie OKISSI",
    generation: 2,
    parentId: "1",
    children: [],
    birthRank: 8,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "11",
    name: "Annie-Flore OKISSI Eps ROWANDJA",
    generation: 2,
    parentId: "1",
    children: [],
    birthRank: 9,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "12",
    name: "Patricia OKISSI",
    generation: 2,
    parentId: "1",
    children: [],
    birthRank: 10,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "13",
    name: "Prisca OKISSI",
    generation: 2,
    parentId: "1",
    children: [],
    birthRank: 11,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "14",
    name: "Marline OKISSI",
    generation: 2,
    parentId: "1",
    children: [],
    birthRank: 12,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
  {
    id: "15",
    name: "Davy OKISSI",
    generation: 2,
    parentId: "1",
    children: [],
    birthRank: 13,
    createdAt: new Date("2024-01-01T00:00:00.000Z"),
  },
];

export const initialNextId = 16;
